# Generated by Django 3.1.7 on 2021-09-09 02:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('rpfs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('Home', 'Home'), ('About', 'About'), ('Contact', 'Contact'), ('Volunteer', 'Volunteer')], default='Home', max_length=10)),
                ('content', models.TextField(blank=True, default=' ', null=True)),
                ('link_text', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
