# Generated by Django 3.1.7 on 2021-09-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpfs', '0002_page_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='page',
            field=models.CharField(choices=[('Home', 'Home'), ('About', 'About'), ('Contact', 'Contact'), ('Volunteer', 'Volunteer'), ('Items', 'Items')], default='Home', max_length=10),
        ),
    ]
